// export const SIGNUP_ROUTE = "/signup"
// export const LOGIN_ROUTE = "/login"
// export const REGISTRATION_ROUTE = "/registration"
// export const COMPANIES_ROUTE = "/companies"
// export const HOME_ROUTE = "/home"